# Generated by Django 5.2.4 on 2025-10-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('active', 'Активний'), ('blocked', 'Заблокований'), ('normal', 'Нормальний')], max_length=20, null=True),
        ),
    ]
