# Generated by Django 5.2.6 on 2025-10-04 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_nikname',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('active', 'Активний'), ('blocked', 'Заблокований'), ('neactive', 'Неактивний')], default='active', max_length=20),
        ),
    ]
