# Generated by Django 5.2.6 on 2025-10-03 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_group_remove_post_like_post_remove_post_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_message',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.group_message'),
        ),
    ]
