# Generated by Django 5.2.6 on 2025-10-03 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_group_message_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_post',
            name='text',
            field=models.TextField(blank=True, default='no text yet', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='posts/media/'),
        ),
    ]
