# Generated by Django 5.2.6 on 2025-10-04 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_comment_post_text_alter_post_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_post',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='group_reaction_message',
            name='reaction',
            field=models.CharField(choices=[('like', '👍'), ('dislike', '👎'), ('funny', '😂'), ('sad', '😢')]),
        ),
        migrations.AlterField(
            model_name='post_reaction',
            name='reaction',
            field=models.CharField(choices=[('like', '👍'), ('dislike', '👎'), ('funny', '😂'), ('sad', '😢')], max_length=10),
        ),
    ]
