# Generated by Django 5.2.6 on 2025-10-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_comment_post_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_post',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='coment_posts/'),
        ),
        migrations.AlterField(
            model_name='group',
            name='image_goroup',
            field=models.ImageField(blank=True, null=True, upload_to='groups/image_groups/'),
        ),
        migrations.AlterField(
            model_name='group_message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='group_message/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='posts/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/avatars/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/covers/'),
        ),
    ]
