# Generated by Django 5.2.6 on 2025-10-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_comment_post_media_alter_group_image_goroup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(upload_to='profiles/avatars/'),
        ),
    ]
