# Generated by Django 5.2.6 on 2025-10-12 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_profile_avatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment_Post',
            new_name='CommentPost',
        ),
        migrations.RenameModel(
            old_name='Group_message',
            new_name='GroupMessage',
        ),
        migrations.RenameModel(
            old_name='Group_Reaction_message',
            new_name='GroupReactionMessage',
        ),
        migrations.RenameModel(
            old_name='Group_users',
            new_name='GroupUser',
        ),
        migrations.RenameModel(
            old_name='Post_reaction',
            new_name='PostReaction',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='image_goroup',
            new_name='image_group',
        ),
        migrations.RemoveField(
            model_name='post',
            name='media',
        ),
        migrations.AddField(
            model_name='group',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MediaPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(blank=True, null=True, upload_to='media_posts/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_posts', to='main.post')),
            ],
        ),
    ]
