# Generated by Django 5.2.6 on 2025-10-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_comment_post_commentpost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(default='no description group'),
        ),
        migrations.AlterField(
            model_name='mediapost',
            name='media',
            field=models.FileField(upload_to='media_posts/'),
        ),
    ]
