# Generated by Django 5.2.6 on 2025-11-14 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_groupmessage_group_alter_groupmessage_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='type',
            field=models.CharField(choices=[('forum', 'forum'), ('chat', 'chat')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
