# Generated by Django 5.2.6 on 2025-12-04 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_group_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cover',
        ),
    ]
